#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Data.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace PlantCreator {
    using namespace System;
    ref class subFamilyDataSet;
    
    
    /// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
    [System::Serializable, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::ComponentModel::ToolboxItem(true), 
    System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedDataSetSchema"), 
    System::Xml::Serialization::XmlRootAttribute(L"subFamilyDataSet"), 
    System::ComponentModel::Design::HelpKeywordAttribute(L"vs.data.DataSet")]
    public ref class subFamilyDataSet : public ::System::Data::DataSet {
        public : ref class ScienceNameDataTable;
        public : ref class ScienceNameRow;
        public : ref class ScienceNameRowChangeEvent;
        
        private: PlantCreator::subFamilyDataSet::ScienceNameDataTable^  tableScienceName;
        
        private: ::System::Data::SchemaSerializationMode _schemaSerializationMode;
        
        public : [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        delegate System::Void ScienceNameRowChangeEventHandler(::System::Object^  sender, PlantCreator::subFamilyDataSet::ScienceNameRowChangeEvent^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        subFamilyDataSet();
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        subFamilyDataSet(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
        System::ComponentModel::Browsable(false), 
        System::ComponentModel::DesignerSerializationVisibility(::System::ComponentModel::DesignerSerializationVisibility::Content)]
        property PlantCreator::subFamilyDataSet::ScienceNameDataTable^  ScienceName {
            PlantCreator::subFamilyDataSet::ScienceNameDataTable^  get();
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
        System::ComponentModel::BrowsableAttribute(true), 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Visible)]
        virtual property ::System::Data::SchemaSerializationMode SchemaSerializationMode {
            ::System::Data::SchemaSerializationMode get() override;
            System::Void set(::System::Data::SchemaSerializationMode value) override;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataTableCollection^  Tables {
            ::System::Data::DataTableCollection^  get() new;
        }
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
        System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
        System::ComponentModel::DesignerSerializationVisibilityAttribute(::System::ComponentModel::DesignerSerializationVisibility::Hidden)]
        property ::System::Data::DataRelationCollection^  Relations {
            ::System::Data::DataRelationCollection^  get() new;
        }
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void InitializeDerivedDataSet() override;
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Data::DataSet^  Clone() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Boolean ShouldSerializeTables() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Boolean ShouldSerializeRelations() override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Void ReadXmlSerializable(::System::Xml::XmlReader^  reader) override;
        
        protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        virtual ::System::Xml::Schema::XmlSchema^  GetSchemaSerializable() override;
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void InitVars();
        
        internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void InitVars(::System::Boolean initTable);
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void InitClass();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Boolean ShouldSerializeScienceName();
        
        private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ::System::Void SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e);
        
        public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        
        public : /// <summary>
///Represents the strongly named DataTable class.
///</summary>
        [System::Serializable, 
        System::Xml::Serialization::XmlSchemaProviderAttribute(L"GetTypedTableSchema")]
        ref class ScienceNameDataTable : public ::System::Data::DataTable, public ::System::Collections::IEnumerable {
            
            private: ::System::Data::DataColumn^  columnScienceNameID;
            
            private: ::System::Data::DataColumn^  columnCategoryID;
            
            private: ::System::Data::DataColumn^  columnScienceName;
            
            private: ::System::Data::DataColumn^  columnParentScienceNameID;
            
            public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            event PlantCreator::subFamilyDataSet::ScienceNameRowChangeEventHandler^  ScienceNameRowChanging;
            
            public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            event PlantCreator::subFamilyDataSet::ScienceNameRowChangeEventHandler^  ScienceNameRowChanged;
            
            public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            event PlantCreator::subFamilyDataSet::ScienceNameRowChangeEventHandler^  ScienceNameRowDeleting;
            
            public: [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            event PlantCreator::subFamilyDataSet::ScienceNameRowChangeEventHandler^  ScienceNameRowDeleted;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ScienceNameDataTable();
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ScienceNameDataTable(::System::Data::DataTable^  table);
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ScienceNameDataTable(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property ::System::Data::DataColumn^  ScienceNameIDColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property ::System::Data::DataColumn^  CategoryIDColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property ::System::Data::DataColumn^  ScienceNameColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property ::System::Data::DataColumn^  ParentScienceNameIDColumn {
                ::System::Data::DataColumn^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0"), 
            System::ComponentModel::Browsable(false)]
            property ::System::Int32 Count {
                ::System::Int32 get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property PlantCreator::subFamilyDataSet::ScienceNameRow^  default [::System::Int32 ] {
                PlantCreator::subFamilyDataSet::ScienceNameRow^  get(::System::Int32 index);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void AddScienceNameRow(PlantCreator::subFamilyDataSet::ScienceNameRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            PlantCreator::subFamilyDataSet::ScienceNameRow^  AddScienceNameRow(System::Int32 CategoryID, System::String^  ScienceName, 
                        System::Int32 ParentScienceNameID);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            PlantCreator::subFamilyDataSet::ScienceNameRow^  FindByScienceNameID(System::Int32 ScienceNameID);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Collections::IEnumerator^  GetEnumerator();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Data::DataTable^  Clone() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Data::DataTable^  CreateInstance() override;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void InitVars();
            
            private: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void InitClass();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            PlantCreator::subFamilyDataSet::ScienceNameRow^  NewScienceNameRow();
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Data::DataRow^  NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Type^  GetRowType() override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Void OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Void OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Void OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) override;
            
            protected: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            virtual ::System::Void OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) override;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void RemoveScienceNameRow(PlantCreator::subFamilyDataSet::ScienceNameRow^  row);
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            static ::System::Xml::Schema::XmlSchemaComplexType^  GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs);
        };
        
        public : /// <summary>
///Represents strongly named DataRow class.
///</summary>
        ref class ScienceNameRow : public ::System::Data::DataRow {
            
            private: PlantCreator::subFamilyDataSet::ScienceNameDataTable^  tableScienceName;
            
            internal: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ScienceNameRow(::System::Data::DataRowBuilder^  rb);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property System::Int32 ScienceNameID {
                System::Int32 get();
                System::Void set(System::Int32 value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property System::Int32 CategoryID {
                System::Int32 get();
                System::Void set(System::Int32 value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property System::String^  ScienceName {
                System::String^  get();
                System::Void set(System::String^  value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property System::Int32 ParentScienceNameID {
                System::Int32 get();
                System::Void set(System::Int32 value);
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Boolean IsCategoryIDNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void SetCategoryIDNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Boolean IsScienceNameNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void SetScienceNameNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Boolean IsParentScienceNameIDNull();
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ::System::Void SetParentScienceNameIDNull();
        };
        
        public : /// <summary>
///Row event argument class
///</summary>
        [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
        ref class ScienceNameRowChangeEvent : public ::System::EventArgs {
            
            private: PlantCreator::subFamilyDataSet::ScienceNameRow^  eventRow;
            
            private: ::System::Data::DataRowAction eventAction;
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute]
            [System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            ScienceNameRowChangeEvent(PlantCreator::subFamilyDataSet::ScienceNameRow^  row, ::System::Data::DataRowAction action);
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property PlantCreator::subFamilyDataSet::ScienceNameRow^  Row {
                PlantCreator::subFamilyDataSet::ScienceNameRow^  get();
            }
            
            public: [System::Diagnostics::DebuggerNonUserCodeAttribute, 
            System::CodeDom::Compiler::GeneratedCodeAttribute(L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")]
            property ::System::Data::DataRowAction Action {
                ::System::Data::DataRowAction get();
            }
        };
    };
}
namespace PlantCreator {
    
    
    inline subFamilyDataSet::subFamilyDataSet() {
        this->BeginInit();
        this->InitClass();
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &PlantCreator::subFamilyDataSet::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        __super::Relations->CollectionChanged += schemaChangedHandler;
        this->EndInit();
    }
    
    inline subFamilyDataSet::subFamilyDataSet(::System::Runtime::Serialization::SerializationInfo^  info, ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataSet(info, context, false) {
        if (this->IsBinarySerialized(info, context) == true) {
            this->InitVars(false);
            ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler1 = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &PlantCreator::subFamilyDataSet::SchemaChanged);
            this->Tables->CollectionChanged += schemaChangedHandler1;
            this->Relations->CollectionChanged += schemaChangedHandler1;
            return;
        }
        ::System::String^  strSchema = (cli::safe_cast<::System::String^  >(info->GetValue(L"XmlSchema", ::System::String::typeid)));
        if (this->DetermineSchemaSerializationMode(info, context) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
            if (ds->Tables[L"ScienceName"] != nullptr) {
                __super::Tables->Add((gcnew PlantCreator::subFamilyDataSet::ScienceNameDataTable(ds->Tables[L"ScienceName"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXmlSchema((gcnew ::System::Xml::XmlTextReader((gcnew ::System::IO::StringReader(strSchema)))));
        }
        this->GetSerializationData(info, context);
        ::System::ComponentModel::CollectionChangeEventHandler^  schemaChangedHandler = gcnew ::System::ComponentModel::CollectionChangeEventHandler(this, &PlantCreator::subFamilyDataSet::SchemaChanged);
        __super::Tables->CollectionChanged += schemaChangedHandler;
        this->Relations->CollectionChanged += schemaChangedHandler;
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameDataTable^  subFamilyDataSet::ScienceName::get() {
        return this->tableScienceName;
    }
    
    inline ::System::Data::SchemaSerializationMode subFamilyDataSet::SchemaSerializationMode::get() {
        return this->_schemaSerializationMode;
    }
    inline System::Void subFamilyDataSet::SchemaSerializationMode::set(::System::Data::SchemaSerializationMode value) {
        this->_schemaSerializationMode = __identifier(value);
    }
    
    inline ::System::Data::DataTableCollection^  subFamilyDataSet::Tables::get() {
        return __super::Tables;
    }
    
    inline ::System::Data::DataRelationCollection^  subFamilyDataSet::Relations::get() {
        return __super::Relations;
    }
    
    inline ::System::Void subFamilyDataSet::InitializeDerivedDataSet() {
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline ::System::Data::DataSet^  subFamilyDataSet::Clone() {
        PlantCreator::subFamilyDataSet^  cln = (cli::safe_cast<PlantCreator::subFamilyDataSet^  >(__super::Clone()));
        cln->InitVars();
        cln->SchemaSerializationMode = this->SchemaSerializationMode;
        return cln;
    }
    
    inline ::System::Boolean subFamilyDataSet::ShouldSerializeTables() {
        return false;
    }
    
    inline ::System::Boolean subFamilyDataSet::ShouldSerializeRelations() {
        return false;
    }
    
    inline ::System::Void subFamilyDataSet::ReadXmlSerializable(::System::Xml::XmlReader^  reader) {
        if (this->DetermineSchemaSerializationMode(reader) == ::System::Data::SchemaSerializationMode::IncludeSchema) {
            this->Reset();
            ::System::Data::DataSet^  ds = (gcnew ::System::Data::DataSet());
            ds->ReadXml(reader);
            if (ds->Tables[L"ScienceName"] != nullptr) {
                __super::Tables->Add((gcnew PlantCreator::subFamilyDataSet::ScienceNameDataTable(ds->Tables[L"ScienceName"])));
            }
            this->DataSetName = ds->DataSetName;
            this->Prefix = ds->Prefix;
            this->Namespace = ds->Namespace;
            this->Locale = ds->Locale;
            this->CaseSensitive = ds->CaseSensitive;
            this->EnforceConstraints = ds->EnforceConstraints;
            this->Merge(ds, false, ::System::Data::MissingSchemaAction::Add);
            this->InitVars();
        }
        else {
            this->ReadXml(reader);
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchema^  subFamilyDataSet::GetSchemaSerializable() {
        ::System::IO::MemoryStream^  stream = (gcnew ::System::IO::MemoryStream());
        this->WriteXmlSchema((gcnew ::System::Xml::XmlTextWriter(stream, nullptr)));
        stream->Position = 0;
        return ::System::Xml::Schema::XmlSchema::Read((gcnew ::System::Xml::XmlTextReader(stream)), nullptr);
    }
    
    inline ::System::Void subFamilyDataSet::InitVars() {
        this->InitVars(true);
    }
    
    inline ::System::Void subFamilyDataSet::InitVars(::System::Boolean initTable) {
        this->tableScienceName = (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameDataTable^  >(__super::Tables[L"ScienceName"]));
        if (initTable == true) {
            if (this->tableScienceName != nullptr) {
                this->tableScienceName->InitVars();
            }
        }
    }
    
    inline ::System::Void subFamilyDataSet::InitClass() {
        this->DataSetName = L"subFamilyDataSet";
        this->Prefix = L"";
        this->Namespace = L"http://tempuri.org/subFamilyDataSet.xsd";
        this->EnforceConstraints = true;
        this->SchemaSerializationMode = ::System::Data::SchemaSerializationMode::IncludeSchema;
        this->tableScienceName = (gcnew PlantCreator::subFamilyDataSet::ScienceNameDataTable());
        __super::Tables->Add(this->tableScienceName);
    }
    
    inline ::System::Boolean subFamilyDataSet::ShouldSerializeScienceName() {
        return false;
    }
    
    inline ::System::Void subFamilyDataSet::SchemaChanged(::System::Object^  sender, ::System::ComponentModel::CollectionChangeEventArgs^  e) {
        if (e->Action == ::System::ComponentModel::CollectionChangeAction::Remove) {
            this->InitVars();
        }
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  subFamilyDataSet::GetTypedDataSetSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        PlantCreator::subFamilyDataSet^  ds = (gcnew PlantCreator::subFamilyDataSet());
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        ::System::Xml::Schema::XmlSchemaAny^  any = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any->Namespace = ds->Namespace;
        sequence->Items->Add(any);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline subFamilyDataSet::ScienceNameDataTable::ScienceNameDataTable() {
        this->TableName = L"ScienceName";
        this->BeginInit();
        this->InitClass();
        this->EndInit();
    }
    
    inline subFamilyDataSet::ScienceNameDataTable::ScienceNameDataTable(::System::Data::DataTable^  table) {
        this->TableName = table->TableName;
        if (table->CaseSensitive != table->DataSet->CaseSensitive) {
            this->CaseSensitive = table->CaseSensitive;
        }
        if (table->Locale->ToString() != table->DataSet->Locale->ToString()) {
            this->Locale = table->Locale;
        }
        if (table->Namespace != table->DataSet->Namespace) {
            this->Namespace = table->Namespace;
        }
        this->Prefix = table->Prefix;
        this->MinimumCapacity = table->MinimumCapacity;
    }
    
    inline subFamilyDataSet::ScienceNameDataTable::ScienceNameDataTable(::System::Runtime::Serialization::SerializationInfo^  info, 
                ::System::Runtime::Serialization::StreamingContext context) : 
            ::System::Data::DataTable(info, context) {
        this->InitVars();
    }
    
    inline ::System::Data::DataColumn^  subFamilyDataSet::ScienceNameDataTable::ScienceNameIDColumn::get() {
        return this->columnScienceNameID;
    }
    
    inline ::System::Data::DataColumn^  subFamilyDataSet::ScienceNameDataTable::CategoryIDColumn::get() {
        return this->columnCategoryID;
    }
    
    inline ::System::Data::DataColumn^  subFamilyDataSet::ScienceNameDataTable::ScienceNameColumn::get() {
        return this->columnScienceName;
    }
    
    inline ::System::Data::DataColumn^  subFamilyDataSet::ScienceNameDataTable::ParentScienceNameIDColumn::get() {
        return this->columnParentScienceNameID;
    }
    
    inline ::System::Int32 subFamilyDataSet::ScienceNameDataTable::Count::get() {
        return this->Rows->Count;
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameRow^  subFamilyDataSet::ScienceNameDataTable::default::get(::System::Int32 index) {
        return (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(this->Rows[index]));
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::AddScienceNameRow(PlantCreator::subFamilyDataSet::ScienceNameRow^  row) {
        this->Rows->Add(row);
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameRow^  subFamilyDataSet::ScienceNameDataTable::AddScienceNameRow(System::Int32 CategoryID, 
                System::String^  ScienceName, System::Int32 ParentScienceNameID) {
        PlantCreator::subFamilyDataSet::ScienceNameRow^  rowScienceNameRow = (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(this->NewRow()));
        cli::array< ::System::Object^  >^  columnValuesArray = gcnew cli::array< ::System::Object^  >(4) {nullptr, CategoryID, 
            ScienceName, ParentScienceNameID};
        rowScienceNameRow->ItemArray = columnValuesArray;
        this->Rows->Add(rowScienceNameRow);
        return rowScienceNameRow;
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameRow^  subFamilyDataSet::ScienceNameDataTable::FindByScienceNameID(System::Int32 ScienceNameID) {
        return (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(this->Rows->Find(gcnew cli::array< System::Object^  >(1) {ScienceNameID})));
    }
    
    inline ::System::Collections::IEnumerator^  subFamilyDataSet::ScienceNameDataTable::GetEnumerator() {
        return this->Rows->GetEnumerator();
    }
    
    inline ::System::Data::DataTable^  subFamilyDataSet::ScienceNameDataTable::Clone() {
        PlantCreator::subFamilyDataSet::ScienceNameDataTable^  cln = (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameDataTable^  >(__super::Clone()));
        cln->InitVars();
        return cln;
    }
    
    inline ::System::Data::DataTable^  subFamilyDataSet::ScienceNameDataTable::CreateInstance() {
        return (gcnew PlantCreator::subFamilyDataSet::ScienceNameDataTable());
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::InitVars() {
        this->columnScienceNameID = __super::Columns[L"ScienceNameID"];
        this->columnCategoryID = __super::Columns[L"CategoryID"];
        this->columnScienceName = __super::Columns[L"ScienceName"];
        this->columnParentScienceNameID = __super::Columns[L"ParentScienceNameID"];
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::InitClass() {
        this->columnScienceNameID = (gcnew ::System::Data::DataColumn(L"ScienceNameID", ::System::Int32::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnScienceNameID);
        this->columnCategoryID = (gcnew ::System::Data::DataColumn(L"CategoryID", ::System::Int32::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnCategoryID);
        this->columnScienceName = (gcnew ::System::Data::DataColumn(L"ScienceName", ::System::String::typeid, nullptr, ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnScienceName);
        this->columnParentScienceNameID = (gcnew ::System::Data::DataColumn(L"ParentScienceNameID", ::System::Int32::typeid, nullptr, 
            ::System::Data::MappingType::Element));
        __super::Columns->Add(this->columnParentScienceNameID);
        this->Constraints->Add((gcnew ::System::Data::UniqueConstraint(L"Constraint1", gcnew cli::array< ::System::Data::DataColumn^  >(1) {this->columnScienceNameID}, 
                true)));
        this->columnScienceNameID->AutoIncrement = true;
        this->columnScienceNameID->AllowDBNull = false;
        this->columnScienceNameID->Unique = true;
        this->columnScienceName->MaxLength = 255;
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameRow^  subFamilyDataSet::ScienceNameDataTable::NewScienceNameRow() {
        return (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(this->NewRow()));
    }
    
    inline ::System::Data::DataRow^  subFamilyDataSet::ScienceNameDataTable::NewRowFromBuilder(::System::Data::DataRowBuilder^  builder) {
        return (gcnew PlantCreator::subFamilyDataSet::ScienceNameRow(builder));
    }
    
    inline ::System::Type^  subFamilyDataSet::ScienceNameDataTable::GetRowType() {
        return PlantCreator::subFamilyDataSet::ScienceNameRow::typeid;
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::OnRowChanged(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanged(e);
        {
            this->ScienceNameRowChanged(this, (gcnew PlantCreator::subFamilyDataSet::ScienceNameRowChangeEvent((cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::OnRowChanging(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowChanging(e);
        {
            this->ScienceNameRowChanging(this, (gcnew PlantCreator::subFamilyDataSet::ScienceNameRowChangeEvent((cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::OnRowDeleted(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleted(e);
        {
            this->ScienceNameRowDeleted(this, (gcnew PlantCreator::subFamilyDataSet::ScienceNameRowChangeEvent((cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::OnRowDeleting(::System::Data::DataRowChangeEventArgs^  e) {
        __super::OnRowDeleting(e);
        {
            this->ScienceNameRowDeleting(this, (gcnew PlantCreator::subFamilyDataSet::ScienceNameRowChangeEvent((cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameRow^  >(e->Row)), 
                    e->Action)));
        }
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameDataTable::RemoveScienceNameRow(PlantCreator::subFamilyDataSet::ScienceNameRow^  row) {
        this->Rows->Remove(row);
    }
    
    inline ::System::Xml::Schema::XmlSchemaComplexType^  subFamilyDataSet::ScienceNameDataTable::GetTypedTableSchema(::System::Xml::Schema::XmlSchemaSet^  xs) {
        ::System::Xml::Schema::XmlSchemaComplexType^  type = (gcnew ::System::Xml::Schema::XmlSchemaComplexType());
        ::System::Xml::Schema::XmlSchemaSequence^  sequence = (gcnew ::System::Xml::Schema::XmlSchemaSequence());
        PlantCreator::subFamilyDataSet^  ds = (gcnew PlantCreator::subFamilyDataSet());
        ::System::Xml::Schema::XmlSchemaAny^  any1 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any1->Namespace = L"http://www.w3.org/2001/XMLSchema";
        any1->MinOccurs = ::System::Decimal(0);
        any1->MaxOccurs = ::System::Decimal::MaxValue;
        any1->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any1);
        ::System::Xml::Schema::XmlSchemaAny^  any2 = (gcnew ::System::Xml::Schema::XmlSchemaAny());
        any2->Namespace = L"urn:schemas-microsoft-com:xml-diffgram-v1";
        any2->MinOccurs = ::System::Decimal(1);
        any2->ProcessContents = ::System::Xml::Schema::XmlSchemaContentProcessing::Lax;
        sequence->Items->Add(any2);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute1 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute1->Name = L"namespace";
        attribute1->FixedValue = ds->Namespace;
        type->Attributes->Add(attribute1);
        ::System::Xml::Schema::XmlSchemaAttribute^  attribute2 = (gcnew ::System::Xml::Schema::XmlSchemaAttribute());
        attribute2->Name = L"tableTypeName";
        attribute2->FixedValue = L"ScienceNameDataTable";
        type->Attributes->Add(attribute2);
        type->Particle = sequence;
        ::System::Xml::Schema::XmlSchema^  dsSchema = ds->GetSchemaSerializable();
        if (xs->Contains(dsSchema->TargetNamespace)) {
            ::System::IO::MemoryStream^  s1 = (gcnew ::System::IO::MemoryStream());
            ::System::IO::MemoryStream^  s2 = (gcnew ::System::IO::MemoryStream());
            try {
                ::System::Xml::Schema::XmlSchema^  schema = nullptr;
                dsSchema->Write(s1);
                for (                ::System::Collections::IEnumerator^  schemas = xs->Schemas(dsSchema->TargetNamespace)->GetEnumerator(); schemas->MoveNext();                 ) {
                    schema = (cli::safe_cast<::System::Xml::Schema::XmlSchema^  >(schemas->Current));
                    s2->SetLength(0);
                    schema->Write(s2);
                    if (s1->Length == s2->Length) {
                        s1->Position = 0;
                        s2->Position = 0;
                        for (                        ; ((s1->Position != s1->Length) 
                                    && (s1->ReadByte() == s2->ReadByte()));                         ) {
                            ;
                        }
                        if (s1->Position == s1->Length) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if (s1 != nullptr) {
                    s1->Close();
                }
                if (s2 != nullptr) {
                    s2->Close();
                }
            }
        }
        xs->Add(dsSchema);
        return type;
    }
    
    
    inline subFamilyDataSet::ScienceNameRow::ScienceNameRow(::System::Data::DataRowBuilder^  rb) : 
            ::System::Data::DataRow(rb) {
        this->tableScienceName = (cli::safe_cast<PlantCreator::subFamilyDataSet::ScienceNameDataTable^  >(this->Table));
    }
    
    inline System::Int32 subFamilyDataSet::ScienceNameRow::ScienceNameID::get() {
        return (cli::safe_cast<::System::Int32 >(this[this->tableScienceName->ScienceNameIDColumn]));
    }
    inline System::Void subFamilyDataSet::ScienceNameRow::ScienceNameID::set(System::Int32 value) {
        this[this->tableScienceName->ScienceNameIDColumn] = value;
    }
    
    inline System::Int32 subFamilyDataSet::ScienceNameRow::CategoryID::get() {
        try {
            return (cli::safe_cast<::System::Int32 >(this[this->tableScienceName->CategoryIDColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"The value for column \'CategoryID\' in table \'ScienceName\' is DBNull.", 
                e));
        }
    }
    inline System::Void subFamilyDataSet::ScienceNameRow::CategoryID::set(System::Int32 value) {
        this[this->tableScienceName->CategoryIDColumn] = value;
    }
    
    inline System::String^  subFamilyDataSet::ScienceNameRow::ScienceName::get() {
        try {
            return (cli::safe_cast<::System::String^  >(this[this->tableScienceName->ScienceNameColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"The value for column \'ScienceName\' in table \'ScienceName\' is DBNull.", 
                e));
        }
    }
    inline System::Void subFamilyDataSet::ScienceNameRow::ScienceName::set(System::String^  value) {
        this[this->tableScienceName->ScienceNameColumn] = value;
    }
    
    inline System::Int32 subFamilyDataSet::ScienceNameRow::ParentScienceNameID::get() {
        try {
            return (cli::safe_cast<::System::Int32 >(this[this->tableScienceName->ParentScienceNameIDColumn]));
        }
        catch (::System::InvalidCastException^ e) {
            throw (gcnew ::System::Data::StrongTypingException(L"The value for column \'ParentScienceNameID\' in table \'ScienceName\' is DBNull.", 
                e));
        }
    }
    inline System::Void subFamilyDataSet::ScienceNameRow::ParentScienceNameID::set(System::Int32 value) {
        this[this->tableScienceName->ParentScienceNameIDColumn] = value;
    }
    
    inline ::System::Boolean subFamilyDataSet::ScienceNameRow::IsCategoryIDNull() {
        return this->IsNull(this->tableScienceName->CategoryIDColumn);
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameRow::SetCategoryIDNull() {
        this[this->tableScienceName->CategoryIDColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean subFamilyDataSet::ScienceNameRow::IsScienceNameNull() {
        return this->IsNull(this->tableScienceName->ScienceNameColumn);
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameRow::SetScienceNameNull() {
        this[this->tableScienceName->ScienceNameColumn] = ::System::Convert::DBNull;
    }
    
    inline ::System::Boolean subFamilyDataSet::ScienceNameRow::IsParentScienceNameIDNull() {
        return this->IsNull(this->tableScienceName->ParentScienceNameIDColumn);
    }
    
    inline ::System::Void subFamilyDataSet::ScienceNameRow::SetParentScienceNameIDNull() {
        this[this->tableScienceName->ParentScienceNameIDColumn] = ::System::Convert::DBNull;
    }
    
    
    inline subFamilyDataSet::ScienceNameRowChangeEvent::ScienceNameRowChangeEvent(PlantCreator::subFamilyDataSet::ScienceNameRow^  row, 
                ::System::Data::DataRowAction action) {
        this->eventRow = row;
        this->eventAction = action;
    }
    
    inline PlantCreator::subFamilyDataSet::ScienceNameRow^  subFamilyDataSet::ScienceNameRowChangeEvent::Row::get() {
        return this->eventRow;
    }
    
    inline ::System::Data::DataRowAction subFamilyDataSet::ScienceNameRowChangeEvent::Action::get() {
        return this->eventAction;
    }
}
